[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.mainnet]
anancoin_airdrop = "sEs461DSnSm3m9ssbWZ6j8WXrWJm96owZsAgwVSVKqB"

[programs.testnet]
anancoin_airdrop = "sEs461DSnSm3m9ssbWZ6j8WXrWJm96owZsAgwVSVKqB"

[programs.devnet]
anancoin_airdrop = "sEs461DSnSm3m9ssbWZ6j8WXrWJm96owZsAgwVSVKqB"

[programs.localnet]
anancoin_airdrop = "sEs461DSnSm3m9ssbWZ6j8WXrWJm96owZsAgwVSVKqB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
